### PR TITLE
Add some docstrings

### PR DESCRIPTION
**Pull request by dawid2193487**
I wasn't sure how to describe some functions.

What is height for in Font::render()?

### CODE REVIEW

**Comment by jackpot51** [comment]
Height is how tall the text should be

**Comment by dawid2193487** [comment]
Isn't text height influenced by the font size?

-----Wiadomość oryginalna-----
Od: "Jeremy Soller" notifications@github.com
Wysłano: ‎2016-‎05-‎16 00:41
Do: "redox-os/orbfont" orbfont@noreply.github.com
DW: "ca1ek" ca1ekowy@gmail.com; "Author" author@noreply.github.com
Temat: Re: [redox-os/orbfont] Add some docstrings (#1)

Height is how tall the text should be

**Comment by jackpot51** [comment]
That is the font size. The height parameter adjusts the font size

**Comment by dawid2193487** [comment]
Oh, I think it should be renamed to font_size or points/dots (I'm not sure which one is used in English). It doesn't change just the height, but also width.

At first I thought it would do something like interline.

-----Wiadomość oryginalna-----
Od: "Jeremy Soller" notifications@github.com
Wysłano: ‎2016-‎05-‎16 00:49
Do: "redox-os/orbfont" orbfont@noreply.github.com
DW: "ca1ek" ca1ekowy@gmail.com; "Author" author@noreply.github.com
Temat: Re: [redox-os/orbfont] Add some docstrings (#1)

That is the font size

**Pull request merged**
